"""Initial migration- Business photo

Revision ID: 406dc3aad75a
Revises: 
Create Date: 2022-10-23 23:38:29.236562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406dc3aad75a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_photo', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('business_photo')

    # ### end Alembic commands ###
