"""Added more business vars

Revision ID: 4b74d767f8d7
Revises: f8465e0fbedb
Create Date: 2022-10-19 13:46:26.613072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b74d767f8d7'
down_revision = 'f8465e0fbedb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('business_email', sa.String(), nullable=True))
    op.add_column('user', sa.Column('business_phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'business_phone')
    op.drop_column('user', 'business_email')
    # ### end Alembic commands ###
