"""empty message

Revision ID: 5a40c0730610
Revises: c51d3bda7306
Create Date: 2022-10-23 23:46:50.750918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a40c0730610'
down_revision = 'c51d3bda7306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_user')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_photo', sa.String(length=20), nullable=False))
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
        batch_op.drop_column('business_photo')

    op.create_table('_alembic_tmp_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=60), nullable=True),
    sa.Column('password', sa.VARCHAR(length=60), nullable=False),
    sa.Column('image_file', sa.VARCHAR(length=20), nullable=False),
    sa.Column('date_registered', sa.DATETIME(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=6), nullable=False),
    sa.Column('is_superadmin', sa.BOOLEAN(), nullable=False),
    sa.Column('current_salary', sa.VARCHAR(length=60), nullable=True),
    sa.Column('occupation', sa.VARCHAR(length=60), nullable=True),
    sa.Column('experience', sa.VARCHAR(length=60), nullable=True),
    sa.Column('date_of_birth', sa.VARCHAR(), nullable=False),
    sa.Column('home_address', sa.VARCHAR(), nullable=True),
    sa.Column('work_address', sa.VARCHAR(), nullable=True),
    sa.Column('is_suspended', sa.BOOLEAN(), nullable=False),
    sa.Column('business_name', sa.VARCHAR(), nullable=True),
    sa.Column('business_email', sa.VARCHAR(), nullable=True),
    sa.Column('business_phone', sa.VARCHAR(), nullable=True),
    sa.Column('business_about', sa.VARCHAR(), nullable=True),
    sa.Column('business_services', sa.VARCHAR(), nullable=True),
    sa.Column('business_images', sa.VARCHAR(), nullable=True),
    sa.Column('business_facebook', sa.VARCHAR(), nullable=True),
    sa.Column('business_twitter', sa.VARCHAR(), nullable=True),
    sa.Column('business_linkedin', sa.VARCHAR(), nullable=True),
    sa.Column('business_whatsapp', sa.VARCHAR(), nullable=True),
    sa.Column('business_photo', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
