"""Member business photos

Revision ID: 6b7cec55cf3a
Revises: 65e67a26d106
Create Date: 2022-10-24 17:23:27.322595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b7cec55cf3a'
down_revision = '65e67a26d106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_product_image_1', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('business_product_image_2', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('business_product_image_3', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('business_product_image_4', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('business_product_image_5', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('business_product_image_6', sa.String(length=20), nullable=True))
        batch_op.drop_column('business_images')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_images', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('business_product_image_6')
        batch_op.drop_column('business_product_image_5')
        batch_op.drop_column('business_product_image_4')
        batch_op.drop_column('business_product_image_3')
        batch_op.drop_column('business_product_image_2')
        batch_op.drop_column('business_product_image_1')

    # ### end Alembic commands ###
