"""empty message

Revision ID: c51d3bda7306
Revises: 406dc3aad75a
Create Date: 2022-10-23 23:46:24.512465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c51d3bda7306'
down_revision = '406dc3aad75a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_photo', sa.String(length=20), nullable=False))
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
        batch_op.drop_column('business_photo')

    # ### end Alembic commands ###
