"""empty message

Revision ID: d8cc40fe6923
Revises: 3248c2a192bc
Create Date: 2022-10-25 08:22:29.638590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8cc40fe6923'
down_revision = '3248c2a192bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_user')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_filled_profile', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('has_filled_profile')

    op.create_table('_alembic_tmp_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=60), nullable=True),
    sa.Column('password', sa.VARCHAR(length=60), nullable=False),
    sa.Column('image_file', sa.VARCHAR(length=20), nullable=False),
    sa.Column('date_registered', sa.DATETIME(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=6), nullable=False),
    sa.Column('is_superadmin', sa.BOOLEAN(), nullable=False),
    sa.Column('current_salary', sa.VARCHAR(length=60), nullable=True),
    sa.Column('occupation', sa.VARCHAR(length=60), nullable=True),
    sa.Column('experience', sa.VARCHAR(length=60), nullable=True),
    sa.Column('date_of_birth', sa.VARCHAR(), nullable=False),
    sa.Column('home_address', sa.VARCHAR(), nullable=True),
    sa.Column('work_address', sa.VARCHAR(), nullable=True),
    sa.Column('is_suspended', sa.BOOLEAN(), nullable=False),
    sa.Column('business_name', sa.VARCHAR(), nullable=True),
    sa.Column('business_email', sa.VARCHAR(), nullable=True),
    sa.Column('business_phone', sa.VARCHAR(), nullable=True),
    sa.Column('business_about', sa.VARCHAR(), nullable=True),
    sa.Column('business_services', sa.VARCHAR(), nullable=True),
    sa.Column('business_facebook', sa.VARCHAR(), nullable=True),
    sa.Column('business_twitter', sa.VARCHAR(), nullable=True),
    sa.Column('business_linkedin', sa.VARCHAR(), nullable=True),
    sa.Column('business_whatsapp', sa.VARCHAR(), nullable=True),
    sa.Column('business_photo', sa.VARCHAR(length=20), nullable=True),
    sa.Column('business_product_image_1', sa.VARCHAR(length=20), nullable=False),
    sa.Column('business_product_image_2', sa.VARCHAR(length=20), nullable=False),
    sa.Column('business_product_image_3', sa.VARCHAR(length=20), nullable=False),
    sa.Column('business_product_image_4', sa.VARCHAR(length=20), nullable=False),
    sa.Column('business_product_image_5', sa.VARCHAR(length=20), nullable=False),
    sa.Column('business_product_image_6', sa.VARCHAR(length=20), nullable=False),
    sa.Column('has_filled_profile', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
