"""fixed address

Revision ID: e07ae3008516
Revises: d8cc40fe6923
Create Date: 2022-10-25 14:27:12.663921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e07ae3008516'
down_revision = 'd8cc40fe6923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_address', sa.String(), nullable=True))
        batch_op.drop_column('home_address')
        batch_op.drop_column('work_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_address', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('home_address', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('business_address')

    # ### end Alembic commands ###
