"""Has filled profile

Revision ID: edae6a4cbe16
Revises: 6b7cec55cf3a
Create Date: 2022-10-25 08:19:22.147352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edae6a4cbe16'
down_revision = '6b7cec55cf3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_filled_profile', sa.Boolean(), nullable=False))
        batch_op.alter_column('business_photo',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('business_product_image_1',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('business_product_image_2',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('business_product_image_3',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('business_product_image_4',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('business_product_image_5',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('business_product_image_6',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('business_product_image_6',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('business_product_image_5',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('business_product_image_4',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('business_product_image_3',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('business_product_image_2',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('business_product_image_1',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('business_photo',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('has_filled_profile')

    # ### end Alembic commands ###
