"""Added business name column

Revision ID: f8465e0fbedb
Revises: bc44eddcc0c3
Create Date: 2022-10-19 13:08:08.257703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8465e0fbedb'
down_revision = 'bc44eddcc0c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('business_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'business_name')
    # ### end Alembic commands ###
