name: Python Flask CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.13

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Set up cPanel deployment
      uses: serverless/github-action-cpanel@v1
      with:
        cpanel-username: ${{ secrets.CPANEL_USERNAME }}
        cpanel-password: ${{ secrets.CPANEL_PASSWORD }}
        cpanel-domain: portal.nasmeoyo.org
        cpanel-app-directory: /home/nasmeoyo/membership_portal

    - name: Deploy to cPanel
      run: |
        cp -r * /home/nasmeoyo/membership_portal


# name: Python Flask CI/CD

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2

#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.x

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt

#     - name: Run tests
#       run: |
#         python -m pytest

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2

#     - name: Set up cPanel deployment
#       uses: serverless/github-action-cpanel@v1
#       with:
#         cpanel-username: ${{ secrets.CPANEL_USERNAME }}
#         cpanel-password: ${{ secrets.CPANEL_PASSWORD }}
#         cpanel-domain: portal.nasmeoyo.org
#         cpanel-app-directory: /home/nasmeoyo/membership_portal

#     - name: Deploy to cPanel
#       run: |
#         cp -r * $CPANEL_APP_DIRECTORY

# name: Publish Website to CPanel
# on:
#   push:
#     branches:
#       - main
# jobs:
#   FTP-Deploy-Action:
#     name: FTP-Deploy-Action
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2.1.0
#       with:
#         fetch-depth: 2
#     - name: FTP-Deploy-Action
#       uses: SamKirkland/FTP-Deploy-Action@3.1.1
#       with:
#         ftp-server: ${{ secrets.FTP_SERVER }}
#         ftp-username: ${{ secrets.FTP_USERNAME }}
#         ftp-password: ${{ secrets.FTP_PASSWORD }}
